hparams = {
    'file_name': "runs_uf8_cnn_lstm_best.txt",
    'args':
        [
            {
                'algo': ['sarsa'],
                'arch': ['cnn_lstm'],
                'env': ['uf8m'],
                'slip_prob': [0.1],
                'max_episode_steps': [1000],
                'batch_size': [64],
                'replay': [True],
                'n_hidden': [32],
                'discounting': [0.99],
                'step_size': [1e-6],
                'trunc': [10],
                'action_cond': ['cat'],
                'uncertainty_decay': [0.95],
                'buffer_size': [100000],
                'total_steps': [6000000],
                'offline_eval_freq': [10000],
                'checkpoint_freq': [20000],
                'save_all_checkpoints': [False],
                'platform': ["gpu"],
                'seed': [(i + 2020) for i in range(5, 30)]
            },
            {
                'algo': ['sarsa'],
                'arch': ['cnn_lstm'],
                'env': ['uf8m'],
                'slip_prob': [0.1],
                'max_episode_steps': [1000],
                'batch_size': [64],
                'replay': [True],
                'n_hidden': [32],
                'discounting': [0.99],
                'step_size': [1e-6],
                'trunc': [5],
                'action_cond': ['cat'],
                'uncertainty_decay': [1.],
                'buffer_size': [100000],
                'total_steps': [6000000],
                'offline_eval_freq': [10000],
                'checkpoint_freq': [20000],
                'save_all_checkpoints': [False],
                'platform': ["gpu"],
                'seed': [(i + 2020) for i in range(5, 30)]
            },
        ]
}
